# Generated by Django 4.2.7 on 2023-11-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=20000)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongtoClassroom', to='educationPortal.classroom')),
                ('givenFiles', models.ManyToManyField(blank=True, to='educationPortal.filemodel')),
            ],
        ),
    ]
