# Generated by Django 4.2.7 on 2023-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0002_addnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnotes',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
