# Generated by Django 4.2.7 on 2023-12-29 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0005_remove_subject_students_user_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='subjects',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
